project:
  name: quickstart-taskcat-ci
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  quickstart-taskcat-ci-test1:
    parameters:
      CodeHostingBucket: au-demo-us-east-1
      ConfigBucket: au-demo-us-west-2
      Email: email@example.com
      GitHubOAuthToken: github-token
      GitHubRepoName: github-repo-name
      GitHubUser: aws-quickstart
      ProdStackConfig: forge-prod-us-west-2.json
      ProdStackName: autodesk-prod
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: quickstart-taskcat-ci/
      ReleaseBranch: master
      SourceRepoBranch: develop
      TemplateFileName: autodesk-forge-master.json
      TestStackConfig: config/test/taskcat_project_override.json
    regions:
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    s3_bucket: ''
    template: templates/taskcat-cicd-pipeline.template.yaml
