project:
  name: quickstart-taskcat-ci
  owner: quickstart-eng@amazon.com
  shorten_stack_name: true
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  quickstart-taskcat-ci-test1:
    parameters:
      CodeHostingBucket: YOUR_CODE_HOSTING_BUCKET
      ConfigBucket: YOUR_CONFIG_HOSTING_BUCKET
      Email: email@example.com
      GitHubOAuthToken: OVERRIDE_THIS
      GitHubRepoName: quickstart-serverless-survey
      GitHubUser: OVERRIDE_THIS
      ProdStackConfig: qs-prod-codepipeline.json
      ProdStackName: survey-prod
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: quickstart-taskcat-ci/
      ReleaseBranch: main
      SourceRepoBranch: develop
      TemplateFileName: serverless-survey.template.yaml
      TestStackConfig: .taskcat_overrides.yml
    regions:
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - eu-west-1
    - eu-west-2
    s3_bucket: ''
    template: templates/taskcat-cicd-pipeline.template.yaml
